version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: user
      DB_NAME: ecommerce
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Optional: Automatically load schema.sql if present
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data:
