services:
  - type: web
    name: ecommerce-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      # Add your other environment variables here